prefix qb: <http://purl.org/linked-data/cube#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
select distinct ?dim 
where { 
  ?dim a qb:DimensionProperty . 
  ?dim rdfs:range skos:Concept . 
  FILTER NOT EXISTS { ?dim qb:codeList [] } 
}
