prefix qb: <http://purl.org/linked-data/cube#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
select distinct ?dim ?v ?list 
where { 
  ?obs qb:dataSet ?ds . 
  ?ds qb:structure ?dsd . 
  ?dsd qb:component ?cs . 
  ?cs qb:componentProperty ?dim . 
  ?dim a qb:DimensionProperty . 
  ?dim qb:codeList ?list . 
  ?list a skos:ConceptScheme . 
  ?obs ?dim ?v . 
  FILTER NOT EXISTS { ?v a skos:Concept . ?v skos:inScheme ?list . } 
}
