#!/bin/bash
# LOD2 Geo Benchmark - simple benchmark execution script
#
# Copyright (c) 2012, CWI (www.cwi.nl). Author: Peter Boncz
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
#    ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# as generated by geoqgen.  basic=0 rtree=1 quad=2 
VARIANT=$1

# warmup=0, power=1, tput={2,4,8,16}
RUN=$2

# the SPARQL client program -- currently only tested for Virtuoso
CLIENT="isql -S 1113"

START=`date -u | awk '{ print $4 }'`
for stream in 01 $(seq -f '%02g' 2 1 $RUN) 
do 
  (for query in $VARIANT/$RUN/$stream/*sparql; do $CLIENT < $query 2>&1 | tee $query.$START.out | tail -2 | head -1; done) | tee $VARIANT/$RUN/$stream/perf.out& 
done
wait
DONE=`date -u | awk '{ print $4 }'`
echo done > $1/$2/$DONE
